# Generated by Django 6.1.1 on 2026-09-13 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_hr_admin',
            field=models.BooleanField(default=False, help_text='Designates whether the user is an HR Admin for their organization.'),
        ),
    ]
